// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1LPISzcR7EQO5pp6T1kQmounHdyjBDFY',
    appId: '1:586034724097:web:b328b3883bdd06585d6f00',
    messagingSenderId: '586034724097',
    projectId: 'laporcepat-c2f3b',
    authDomain: 'laporcepat-c2f3b.firebaseapp.com',
    databaseURL: 'https://laporcepat-c2f3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laporcepat-c2f3b.appspot.com',
    measurementId: 'G-JH1J22NDHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbZdAvIPk8lvBQKXvsIiF0fM8fMAIbjI0',
    appId: '1:586034724097:android:9721b0e15c7419085d6f00',
    messagingSenderId: '586034724097',
    projectId: 'laporcepat-c2f3b',
    databaseURL: 'https://laporcepat-c2f3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laporcepat-c2f3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4pMrhQO_4EU_zRT3V3aOfe_iivPGxGH0',
    appId: '1:586034724097:ios:302ab09cc6e599245d6f00',
    messagingSenderId: '586034724097',
    projectId: 'laporcepat-c2f3b',
    databaseURL: 'https://laporcepat-c2f3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laporcepat-c2f3b.appspot.com',
    iosBundleId: 'com.example.laporcepat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4pMrhQO_4EU_zRT3V3aOfe_iivPGxGH0',
    appId: '1:586034724097:ios:e0c604066af3d01b5d6f00',
    messagingSenderId: '586034724097',
    projectId: 'laporcepat-c2f3b',
    databaseURL: 'https://laporcepat-c2f3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laporcepat-c2f3b.appspot.com',
    iosBundleId: 'com.example.laporcepat.RunnerTests',
  );
}
